"""Add chat_id column to Contatos table

Revision ID: a3bc0b3e2a1e
Revises: 790b827ec8a7
Create Date: 2024-09-11 13:40:49.792583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bc0b3e2a1e'
down_revision: Union[str, None] = '790b827ec8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contatos', sa.Column('chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contatos', 'chat_id')
    # ### end Alembic commands ###
