"""update chat_id column to Contatos table

Revision ID: edffef3b5526
Revises: a3bc0b3e2a1e
Create Date: 2024-09-11 13:56:57.468004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edffef3b5526'
down_revision: Union[str, None] = 'a3bc0b3e2a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contatos', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contatos', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
